#!/bin/bash

# 更新されたサイトをCloudflare Pagesにデプロイ

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📤 QUIVer サイト更新デプロイ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "更新内容:"
echo "✅ すべてのリンクをサブドメインに更新"
echo "✅ https://dashboard.quiver.network"
echo "✅ https://api.quiver.network"
echo "✅ https://playground.quiver.network"
echo "✅ https://explorer.quiver.network"
echo "✅ https://docs.quiver.network"
echo "✅ https://security.quiver.network"
echo "✅ https://quicpair.quiver.network"
echo ""
echo "デプロイコマンド:"
echo "wrangler pages deploy docs --project-name=quiver-network --branch=main"
echo ""
echo "実行してください。ブラウザが開いて認証を求められます。"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "バックエンドサービスのDNS設定ファイル:"
echo "📄 cloudflare-dns-backend.txt"
echo ""
echo "現在の状況:"
echo "• Gateway: ローカル開発中 (localhost:8080)"
echo "• Signal Server: ローカル開発中 (localhost:8081)"
echo "• Bootstrap Nodes: 未デプロイ"
echo "• Registry: 未実装"
echo ""
echo "詳細は current-services.md を参照してください。"