FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git make

WORKDIR /build
COPY aggregator/go.mod aggregator/go.sum ./
RUN go mod download

COPY aggregator/ .
RUN go build -o aggregator cmd/aggregator/main.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates
WORKDIR /app

COPY --from=builder /build/aggregator .

EXPOSE 8081
CMD ["./aggregator"]