FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git make

WORKDIR /build
COPY provider/go.mod provider/go.sum ./
RUN go mod download

COPY provider/ .
RUN go build -o provider cmd/provider/main.go

FROM alpine:latest

RUN apk add --no-cache ca-certificates
WORKDIR /app

COPY --from=builder /build/provider .

EXPOSE 4001/udp
CMD ["./provider"]