name = "quiver-network"
main = "src/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./docs"

[[routes]]
pattern = "api.quiver.network/*"
zone_name = "quiver.network"

[[routes]]
pattern = "blog.quiver.network/*"
zone_name = "quiver.network"

[[routes]]
pattern = "community.quiver.network/*"
zone_name = "quiver.network"

[[routes]]
pattern = "dashboard.quiver.network/*"
zone_name = "quiver.network"

[[routes]]
pattern = "docs.quiver.network/*"
zone_name = "quiver.network"

[[routes]]
pattern = "explorer.quiver.network/*"
zone_name = "quiver.network"

[[routes]]
pattern = "playground.quiver.network/*"
zone_name = "quiver.network"

[[routes]]
pattern = "quicpair.quiver.network/*"
zone_name = "quiver.network"

[[routes]]
pattern = "security.quiver.network/*"
zone_name = "quiver.network"

[[routes]]
pattern = "status.quiver.network/*"
zone_name = "quiver.network"