#!/bin/bash
# Apple Developer証明書ダウンロードガイド

echo "🍎 Apple Developer証明書セットアップガイド"
echo "========================================"
echo ""
echo "証明書がまだない場合は、以下の手順で作成してください："
echo ""
echo "1. Apple Developerアカウントにログイン"
echo "   https://developer.apple.com/account"
echo ""
echo "2. 「Certificates, IDs & Profiles」をクリック"
echo ""
echo "3. 「Certificates」→「+」ボタン"
echo ""
echo "4. 「Developer ID Application」を選択"
echo "   ※ これがインストーラー署名用の証明書です"
echo ""
echo "5. CSR（証明書署名要求）の作成："
echo "   - キーチェーンアクセスを開く"
echo "   - メニュー → 証明書アシスタント → 認証局に証明書を要求"
echo "   - メールアドレスと名前を入力"
echo "   - 「ディスクに保存」を選択"
echo ""
echo "6. 作成したCSRファイルをアップロード"
echo ""
echo "7. 証明書をダウンロードしてダブルクリック"
echo ""
echo "完了したら、このコマンドを実行して確認："
echo "security find-identity -p basic -v | grep 'Developer ID'"
echo ""
echo "証明書が表示されたら、以下を実行："
echo "./scripts/setup-signing.sh"
echo ""

# 現在の証明書を再確認
echo "現在インストールされている証明書:"
echo "================================"
security find-identity -p basic -v | grep -E "(Developer ID|Apple Development)" || echo "証明書が見つかりません"

echo ""
echo "Xcodeがインストールされている場合、自動ダウンロードも可能です:"
echo "Xcode → Settings → Accounts → Manage Certificates → + → Developer ID Application"