name = "quiver-network-stats"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
workers_dev = false
routes = [
  { pattern = "stats.quiver.network/*", zone_name = "quiver.network" },
  { pattern = "api.quiver.network/stats/*", zone_name = "quiver.network" }
]

[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_KV_PREVIEW_ID"

[vars]
ENVIRONMENT = "production"