name: Sync DNS Records

on:
  push:
    branches:
      - main
    paths:
      - 'dns/**'
      - '.github/workflows/dns-sync.yml'
  workflow_dispatch:

jobs:
  validate-dns:
    name: Validate DNS Configuration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install pyyaml jsonschema dnspython
      
      - name: Validate DNS records
        run: |
          python scripts/validate-dns.py

  sync-dns:
    name: Sync DNS to Cloudflare
    runs-on: ubuntu-latest
    needs: validate-dns
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Cloudflare CLI
        run: |
          pip install cloudflare
      
      - name: Sync DNS records
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          python scripts/sync-dns.py
      
      - name: Verify DNS propagation
        run: |
          python scripts/verify-dns.py